// Zonas fijas para elegir al crear/editar un complejo y para filtrar en la
// búsqueda. Antes "zona" era texto libre ("Villa Devoto" vs "villa devoto,
// CABA" no coincidían), lo que rompía el filtro de zona. Ahora todos eligen
// de la misma lista.
export const BARRIOS_CABA = [
  'Agronomía',
  'Almagro',
  'Balvanera',
  'Barracas',
  'Belgrano',
  'Boedo',
  'Caballito',
  'Chacarita',
  'Coghlan',
  'Colegiales',
  'Constitución',
  'Flores',
  'Floresta',
  'La Boca',
  'La Paternal',
  'Liniers',
  'Mataderos',
  'Monte Castro',
  'Monserrat',
  'Nueva Pompeya',
  'Núñez',
  'Palermo',
  'Parque Avellaneda',
  'Parque Chacabuco',
  'Parque Chas',
  'Parque Patricios',
  'Puerto Madero',
  'Recoleta',
  'Retiro',
  'Saavedra',
  'San Cristóbal',
  'San Nicolás',
  'San Telmo',
  'Vélez Sarsfield',
  'Versalles',
  'Villa Crespo',
  'Villa del Parque',
  'Villa Devoto',
  'Villa General Mitre',
  'Villa Lugano',
  'Villa Luro',
  'Villa Ortúzar',
  'Villa Pueyrredón',
  'Villa Real',
  'Villa Riachuelo',
  'Villa Santa Rita',
  'Villa Soldati',
  'Villa Urquiza',
]

// Selección de localidades del Gran Buenos Aires más comunes. Se puede
// ampliar después agregando strings a esta lista, sin tocar nada más.
export const LOCALIDADES_PBA = [
  'Avellaneda',
  'Berazategui',
  'Bernal',
  'Boulogne',
  'Caseros',
  'Castelar',
  'Ciudadela',
  'Don Torcuato',
  'Escobar',
  'Ezeiza',
  'Florencio Varela',
  'Florida',
  'Hurlingham',
  'Ituzaingó',
  'José C. Paz',
  'La Matanza',
  'Lanús',
  'Lomas de Zamora',
  'Malvinas Argentinas',
  'Martínez',
  'Merlo',
  'Moreno',
  'Morón',
  'Olivos',
  'Pilar',
  'Quilmes',
  'Ramos Mejía',
  'San Fernando',
  'San Isidro',
  'San Justo',
  'San Martín',
  'San Miguel',
  'Tigre',
  'Tres de Febrero',
  'Vicente López',
]

export const TODAS_LAS_ZONAS = [...BARRIOS_CABA, ...LOCALIDADES_PBA]
